/*
 * QuartzStreams — payment privacy for the Quartz web wallet.
 *
 * Plain English: this file gives the wallet a never-ending list of
 * fresh addresses (all recoverable from your seed phrase, invisible to
 * anyone reading the chain) plus "payment lanes" — lists of future
 * addresses you hand to a payer or an accountant. Addresses only, no
 * keys: they can pay you (or watch you), never rob you.
 *
 * Byte-for-byte port of the reference node:
 *   reference-node/quartz/quantum_crypto.py  (WOTS+ w=4, 67 chains, Merkle h=8)
 *   reference-node/quartz/wallet.py          (StreamWallet / PaymentChannel)
 * Cross-validated against wallet/streams-vectors.json (generated by the
 * Python reference) — see wallet/test-streams.js.
 *
 * No dependencies. Works in the browser (window.QuartzStreams) and in
 * Node (module.exports) for testing.
 */
(function (global) {
  'use strict';

  // ------------------------------------------------------------------
  // Synchronous SHA-256 (fast — a WOTS+ tree is ~275K hashes per address)
  // ------------------------------------------------------------------

  const K = new Uint32Array([
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1,
    0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
    0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786,
    0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147,
    0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
    0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
    0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a,
    0x5b9cca4f, 0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
    0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2
  ]);

  const IV = new Int32Array([
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
    0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19
  ]);

  const _w = new Uint32Array(64);
  const _h = new Int32Array(8);
  const _block = new Uint8Array(64);

  function rotr(x, n) { return (x >>> n) | (x << (32 - n)); }

  function sha256(data) {
    const len = data.length;
    const bitLenLo = (len << 3) >>> 0;
    const bitLenHi = Math.floor(len / 0x20000000);
    const paddedLen = (((len + 8) >> 6) + 1) << 6;
    const padded = new Uint8Array(paddedLen);
    padded.set(data);
    padded[len] = 0x80;
    // 64-bit BIG-ENDIAN bit length in the final 8 bytes
    padded[paddedLen - 8] = (bitLenHi >>> 24) & 0xff;
    padded[paddedLen - 7] = (bitLenHi >>> 16) & 0xff;
    padded[paddedLen - 6] = (bitLenHi >>> 8) & 0xff;
    padded[paddedLen - 5] = bitLenHi & 0xff;
    padded[paddedLen - 4] = (bitLenLo >>> 24) & 0xff;
    padded[paddedLen - 3] = (bitLenLo >>> 16) & 0xff;
    padded[paddedLen - 2] = (bitLenLo >>> 8) & 0xff;
    padded[paddedLen - 1] = bitLenLo & 0xff;

    _h.set(IV);
    for (let off = 0; off < paddedLen; off += 64) {
      for (let t = 0; t < 16; t++) {
        const i = off + (t << 2);
        _w[t] = (padded[i] << 24) | (padded[i + 1] << 16) |
                (padded[i + 2] << 8) | padded[i + 3];
      }
      for (let t = 16; t < 64; t++) {
        const w2 = _w[t - 2], w15 = _w[t - 15];
        const s0 = rotr(w15, 7) ^ rotr(w15, 18) ^ (w15 >>> 3);
        const s1 = rotr(w2, 17) ^ rotr(w2, 19) ^ (w2 >>> 10);
        _w[t] = (_w[t - 16] + s0 + _w[t - 7] + s1) | 0;
      }
      let a = _h[0], b = _h[1], c = _h[2], d = _h[3];
      let e = _h[4], f = _h[5], g = _h[6], h = _h[7];
      for (let t = 0; t < 64; t++) {
        const S1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25);
        const ch = (e & f) ^ (~e & g);
        const t1 = (h + S1 + ch + K[t] + _w[t]) | 0;
        const S0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22);
        const maj = (a & b) ^ (a & c) ^ (b & c);
        const t2 = (S0 + maj) | 0;
        h = g; g = f; f = e; e = (d + t1) | 0;
        d = c; c = b; b = a; a = (t1 + t2) | 0;
      }
      _h[0] = (_h[0] + a) | 0; _h[1] = (_h[1] + b) | 0;
      _h[2] = (_h[2] + c) | 0; _h[3] = (_h[3] + d) | 0;
      _h[4] = (_h[4] + e) | 0; _h[5] = (_h[5] + f) | 0;
      _h[6] = (_h[6] + g) | 0; _h[7] = (_h[7] + h) | 0;
    }
    const out = new Uint8Array(32);
    for (let i = 0; i < 8; i++) {
      out[i << 2] = (_h[i] >>> 24) & 0xff;
      out[(i << 2) + 1] = (_h[i] >>> 16) & 0xff;
      out[(i << 2) + 2] = (_h[i] >>> 8) & 0xff;
      out[(i << 2) + 3] = _h[i] & 0xff;
    }
    return out;
  }

  // ------------------------------------------------------------------
  // Byte helpers
  // ------------------------------------------------------------------

  function le32(n) {
    return new Uint8Array([n & 0xff, (n >>> 8) & 0xff, (n >>> 16) & 0xff, (n >>> 24) & 0xff]);
  }

  function concat() {
    let total = 0;
    for (let i = 0; i < arguments.length; i++) total += arguments[i].length;
    const out = new Uint8Array(total);
    let pos = 0;
    for (let i = 0; i < arguments.length; i++) { out.set(arguments[i], pos); pos += arguments[i].length; }
    return out;
  }

  function utf8(s) { return new TextEncoder().encode(s); }

  function bytesToHex(bytes) {
    let s = '';
    for (let i = 0; i < bytes.length; i++) s += bytes[i].toString(16).padStart(2, '0');
    return s;
  }

  function hexToBytes(hex) {
    const out = new Uint8Array(hex.length >> 1);
    for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.substr(i << 1, 2), 16);
    return out;
  }

  function arraysEqual(a, b) {
    if (a.length !== b.length) return false;
    for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
    return true;
  }

  // ------------------------------------------------------------------
  // Base58 (same alphabet/behavior as crypto.js)
  // ------------------------------------------------------------------

  const BASE58 = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';

  function base58Encode(bytes) {
    let num = 0n;
    for (const b of bytes) num = (num << 8n) | BigInt(b);
    let result = '';
    while (num > 0n) {
      result = BASE58[Number(num % 58n)] + result;
      num = num / 58n;
    }
    for (const b of bytes) { if (b === 0) result = '1' + result; else break; }
    return result;
  }

  function base58Decode(str) {
    let num = 0n;
    for (const ch of str) {
      const idx = BASE58.indexOf(ch);
      if (idx === -1) throw new Error('invalid base58 char: ' + ch);
      num = num * 58n + BigInt(idx);
    }
    const bytes = [];
    while (num > 0n) { bytes.unshift(Number(num & 0xffn)); num >>= 8n; }
    for (const ch of str) { if (ch === '1') bytes.unshift(0); else break; }
    return new Uint8Array(bytes);
  }

  // ------------------------------------------------------------------
  // Address encoding (identical to node public_key_to_address)
  // ------------------------------------------------------------------

  function rootToAddress(root, mainnet = true) {
    const prefix = mainnet ? 0x3B : 0x7F;
    const h = sha256(root).slice(0, 20);
    const payload = new Uint8Array(21);
    payload[0] = prefix;
    payload.set(h, 1);
    const ck = sha256(sha256(payload)).slice(0, 4);
    const addr = new Uint8Array(25);
    addr.set(payload, 0);
    addr.set(ck, 21);
    return base58Encode(addr);
  }

  function validateAddress(address) {
    try {
      const decoded = base58Decode(address);
      if (decoded.length !== 25) return null;
      const payload = decoded.slice(0, 21);
      const checksum = decoded.slice(21);
      const expected = sha256(sha256(payload)).slice(0, 4);
      if (!arraysEqual(checksum, expected)) return null;
      return { mainnet: decoded[0] === 0x3B };
    } catch (e) { return null; }
  }

  // ------------------------------------------------------------------
  // WOTS+ / Merkle (port of quantum_crypto.py, w=4, 67 chains, h=8)
  // ------------------------------------------------------------------

  const TOTAL_CHAINS = 67;
  const CHAIN_LEN = 15;
  const MERKLE_LEAVES = 256;

  function prfChain(kSeed, i) { return sha256(concat(kSeed, le32(i))); }

  function wotsPubkey(kSeed) {
    const pub = new Uint8Array(TOTAL_CHAINS * 32);
    for (let c = 0; c < TOTAL_CHAINS; c++) {
      let v = prfChain(kSeed, c);
      for (let h = 0; h < CHAIN_LEN; h++) v = sha256(v);
      pub.set(v, c * 32);
    }
    return pub;
  }

  function generateQuantumAddressRoot(seed) {
    const leaves = new Array(MERKLE_LEAVES);
    for (let k = 0; k < MERKLE_LEAVES; k++) {
      const kSeed = sha256(concat(seed, le32(k)));
      leaves[k] = sha256(wotsPubkey(kSeed));
    }
    let cur = leaves;
    while (cur.length > 1) {
      const next = new Array(cur.length >> 1);
      for (let i = 0; i < cur.length; i += 2) {
        next[i >> 1] = sha256(concat(cur[i], cur[i + 1]));
      }
      cur = next;
    }
    return cur[0];
  }

  // UI-friendly variant: yields to the event loop so the page stays alive.
  async function generateQuantumAddressRootAsync(seed, onProgress) {
    const leaves = new Array(MERKLE_LEAVES);
    for (let k = 0; k < MERKLE_LEAVES; k++) {
      const kSeed = sha256(concat(seed, le32(k)));
      leaves[k] = sha256(wotsPubkey(kSeed));
      if ((k & 7) === 7) {
        if (onProgress) onProgress(k + 1, MERKLE_LEAVES);
        await new Promise(r => setTimeout(r, 0));
      }
    }
    let cur = leaves;
    while (cur.length > 1) {
      const next = new Array(cur.length >> 1);
      for (let i = 0; i < cur.length; i += 2) next[i >> 1] = sha256(concat(cur[i], cur[i + 1]));
      cur = next;
    }
    return cur[0];
  }

  // ------------------------------------------------------------------
  // StreamWallet — never reuses an address
  // ------------------------------------------------------------------

  class StreamWallet {
    constructor(seed, opts = {}) {
      if (!(seed instanceof Uint8Array) || seed.length !== 32) {
        throw new Error('stream seed must be 32 bytes');
      }
      this.seed = seed;
      this.mainnet = opts.mainnet !== false;
      this.cursor = opts.cursor || 0;
      this._roots = [];
    }

    accountSeed(index) {
      return sha256(concat(utf8('qz/account'), this.seed, le32(index)));
    }

    rootAt(index) {
      if (!(index in this._roots)) this._roots[index] = generateQuantumAddressRoot(this.accountSeed(index));
      return this._roots[index];
    }

    addressAt(index) { return rootToAddress(this.rootAt(index), this.mainnet); }

    nextAddress() { return this.addressAt(this.cursor++); }

    issuedCount() { return this.cursor; }

    currentAddress() { return this.cursor > 0 ? this.addressAt(this.cursor - 1) : null; }

    async currentAddressFresh() {  // derive without blocking the UI
      const i = this.cursor - 1;
      if (i < 0) return null;
      if (!(i in this._roots)) {
        this._roots[i] = await generateQuantumAddressRootAsync(this.accountSeed(i));
      }
      return rootToAddress(this._roots[i], this.mainnet);
    }

    async nextAddressFresh() {
      const i = this.cursor++;
      if (!(i in this._roots)) {
        this._roots[i] = await generateQuantumAddressRootAsync(this.accountSeed(i));
      }
      return rootToAddress(this._roots[i], this.mainnet);
    }
  }

  // ------------------------------------------------------------------
  // PaymentChannel — a private lane between two parties
  // ------------------------------------------------------------------

  class PaymentChannel {
    constructor(channelSeed, channelId = 0, mainnet = true) {
      this.channelSeed = channelSeed;
      this.channelId = channelId;
      this.mainnet = mainnet;
      this._roots = [];
    }

    /** Receiver-side: lane derived from YOUR wallet seed (only you can spend). */
    static fromWallet(walletSeed, channelId = 0, mainnet = true) {
      return new PaymentChannel(
        sha256(concat(utf8('qz/channel'), walletSeed, le32(channelId))),
        channelId, mainnet);
    }

    /** Both ends are yours (sensor ↔ wallet, data logs). Anyone holding the
     *  secret can spend — never use this for receiving from strangers. */
    static fromSharedSecret(secret, channelId = 0, mainnet = true) {
      return new PaymentChannel(
        sha256(concat(utf8('qz/shared'), secret)),
        channelId, mainnet);
    }

    streamSeed(i) {
      return sha256(concat(utf8('qz/stream'), this.channelSeed, le32(i)));
    }

    rootAt(i) {
      if (!(i in this._roots)) this._roots[i] = generateQuantumAddressRoot(this.streamSeed(i));
      return this._roots[i];
    }

    addressAt(i) { return rootToAddress(this.rootAt(i), this.mainnet); }

    /** First n addresses, yielding to the UI between addresses. */
    async addresses(n, onProgress) {
      const out = [];
      for (let i = 0; i < n; i++) {
        if (!(i in this._roots)) {
          this._roots[i] = await generateQuantumAddressRootAsync(this.streamSeed(i));
        }
        out.push(rootToAddress(this._roots[i], this.mainnet));
        if (onProgress) onProgress(i + 1, n);
        await new Promise(r => setTimeout(r, 0));
      }
      return out;
    }

    /** Hand this to your payer — or your accountant. Addresses only. */
    async exportBundle(n, onProgress) {
      const addresses = await this.addresses(n, onProgress);
      return {
        v: 1,
        type: 'quartz/payment-bundle',
        channel: this.channelId,
        net: this.mainnet ? 'main' : 'test',
        count: n,
        addresses
      };
    }
  }

  // ------------------------------------------------------------------
  // ChannelBundle — the payer's / auditor's side (addresses only)
  // ------------------------------------------------------------------

  class ChannelBundle {
    constructor(channelId, mainnet, addresses) {
      for (const a of addresses) {
        const info = validateAddress(a);
        if (!info || info.mainnet !== mainnet) {
          throw new Error('invalid address in bundle: ' + a);
        }
      }
      this.channelId = channelId;
      this.mainnet = mainnet;
      this.addresses = addresses.slice();
      this._cursor = 0;
    }

    nextAddress() {
      if (this._cursor >= this.addresses.length) {
        throw new Error('bundle exhausted — ask the receiver for a fresh one');
      }
      return this.addresses[this._cursor++];
    }

    remaining() { return this.addresses.length - this._cursor; }
  }

  function loadBundle(data) {
    if (typeof data === 'string') data = JSON.parse(data);
    if (!data || data.type !== 'quartz/payment-bundle') {
      throw new Error('not a quartz payment bundle');
    }
    return new ChannelBundle(
      parseInt(data.channel, 10),
      data.net === 'main',
      data.addresses
    );
  }

  // ------------------------------------------------------------------
  // Mnemonic bridge — one seed phrase backs your whole stream.
  // Same PBKDF2 params as crypto.js mnemonicToSeed (standard BIP39).
  // ------------------------------------------------------------------

  async function streamsSeedFromMnemonicWords(words, passphrase = '') {
    const enc = new TextEncoder();
    const keyMaterial = await crypto.subtle.importKey(
      'raw', enc.encode(words.join(' ')),
      { name: 'PBKDF2' }, false, ['deriveBits']
    );
    const mnemonicSeed = new Uint8Array(await crypto.subtle.deriveBits(
      { name: 'PBKDF2', salt: enc.encode('mnemonic' + passphrase), iterations: 2048, hash: 'SHA-512' },
      keyMaterial, 512
    ));
    return sha256(concat(utf8('qz/streams'), mnemonicSeed));
  }

  // ------------------------------------------------------------------

  const api = {
    sha256, le32, concat, utf8, bytesToHex, hexToBytes,
    base58Encode, base58Decode, rootToAddress, validateAddress,
    generateQuantumAddressRoot, generateQuantumAddressRootAsync,
    StreamWallet, PaymentChannel, ChannelBundle, loadBundle,
    streamsSeedFromMnemonicWords
  };

  global.QuartzStreams = api;
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})(typeof self !== 'undefined' ? self : globalThis);
