/*
 * Cross-validation for streams.js against the Python reference node.
 * Vectors: streams-vectors.json (generated by reference-node/quartz).
 *
 * Run: node test-streams.js
 * If this fails, the web wallet and the chain have diverged.
 */
'use strict';

const S = require('./streams.js');
const fs = require('fs');
const path = require('path');

const V = JSON.parse(fs.readFileSync(path.join(__dirname, 'streams-vectors.json'), 'utf8'));

let passed = 0, failed = 0;
function check(name, actual, expected) {
  const ok = JSON.stringify(actual) === JSON.stringify(expected);
  if (ok) { passed++; console.log('  ok  ' + name); }
  else { failed++; console.log('FAIL  ' + name + '\n      got:  ' + JSON.stringify(actual) + '\n      want: ' + JSON.stringify(expected)); }
}

async function main() {
  // --- SHA-256 sanity (NIST vectors) ---
  const enc = new TextEncoder();
  check('sha256("abc")', S.bytesToHex(S.sha256(enc.encode('abc'))),
    'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');
  check('sha256("")', S.bytesToHex(S.sha256(new Uint8Array(0))),
    'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855');
  check('sha256(448-bit msg)', S.bytesToHex(S.sha256(enc.encode('abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq'))),
    '248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1');

  // --- Stream wallet (raw seed) ---
  const seed = S.hexToBytes(V.seed_hex);
  const w = new S.StreamWallet(seed);
  check('account_seed(0)', S.bytesToHex(w.accountSeed(0)), V.account_seed_0);
  check('root(0)', S.bytesToHex(w.rootAt(0)), V.root_0);
  check('stream addresses 0-2', [0, 1, 2].map(i => w.addressAt(i)), V.stream_addresses);
  check('rotation never repeats', new Set([w.nextAddress(), w.nextAddress(), w.nextAddress()]).size, 3);

  // --- Payment channel from wallet (receiver side) ---
  const ch = S.PaymentChannel.fromWallet(seed, 41);
  check('channel 41 stream_seed(0)', S.bytesToHex(ch.streamSeed(0)), V.channel_41.stream_seed_0);
  check('channel 41 addresses', [0, 1, 2].map(i => ch.addressAt(i)), V.channel_41.addresses);

  // --- Shared-secret flavor (own devices only) ---
  const sh = S.PaymentChannel.fromSharedSecret(new TextEncoder().encode('s3cret'), 1);
  check('shared addresses', [0, 1].map(i => sh.addressAt(i)), V.shared.addresses);

  // --- Mnemonic bridge (same words → same stream as the seed phrase) ---
  const mseed = await S.streamsSeedFromMnemonicWords(V.mnemonic.words);
  check('mnemonic stream seed', S.bytesToHex(mseed), V.mnemonic.stream_seed);
  const mw = new S.StreamWallet(mseed);
  check('mnemonic address(0)', mw.addressAt(0), V.mnemonic.address_0);

  // --- Bundles (payer / auditor side) ---
  const bundle = S.loadBundle(JSON.stringify(V.bundle));
  check('bundle loads with addresses', bundle.addresses, V.bundle.addresses);
  check('bundle next() iterates in order',
    [bundle.nextAddress(), bundle.nextAddress()], V.bundle.addresses.slice(0, 2));
  check('bundle remaining', bundle.remaining(), 1);

  const tampered = JSON.parse(JSON.stringify(V.bundle));
  tampered.addresses[1] = 'Qnotarealaddress';
  let threw = false;
  try { S.loadBundle(tampered); } catch (e) { threw = true; }
  check('tampered bundle rejected', threw, true);

  // --- Address validation ---
  check('validateAddress accepts valid', !!S.validateAddress(V.stream_addresses[0]), true);
  check('validateAddress rejects garbage', S.validateAddress('Qgarbage'), null);

  console.log(failed === 0 ? `\nALL ${passed} CHECKS PASSED` : `\n${failed} FAILED, ${passed} passed`);
  process.exit(failed === 0 ? 0 : 1);
}

main().catch(e => { console.error(e); process.exit(1); });
