package com.quartz.wallet.crypto

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Cross-implementation vectors — generated by the reference node
 * (quartz/crypto.py + firmware word packing). If these fail, the app
 * and the chain have diverged.
 */
class QuartzCryptoTest {

    // Generated: entropy → words (firmware packing), keys, address (node public_key_to_address)
    private val testEntropy = "9f6b8a5c3d2e1f0a7b4c5d6e7f8091a2"
    private val testWords = listOf(
        "panda", "fox", "novel", "kid", "tiger", "lunch",
        "unfold", "merry", "hover", "winter", "caught", "dynamic"
    )
    private val testPriv = "8e97fe18c359faf9e6011a168c9a9845074fe61ac66bd8fa91a13d4e25d36be2"
    private val testPub = "d76f4e21b24a6c389186ed4c953ce11525b5ee8c832aa73887d58d84e36455df"
    private val testAddr = "R22Shn2r9Bsq2s4BATYF7NJNAyi3kjKuXc"

    private fun hex(s: String): ByteArray = s.chunked(2).map { it.toInt(16).toByte() }.toByteArray()

    @Test
    fun `entropy to words matches firmware`() {
        assertEquals(testWords, QuartzCrypto.entropyToWords(hex(testEntropy)))
    }

    @Test
    fun `words to entropy round trips`() {
        assertEquals(hex(testEntropy).toList(), QuartzCrypto.wordsToEntropy(testWords).toList())
    }

    @Test
    fun `tampered word is rejected`() {
        val bad = testWords.toMutableList()
        bad[3] = "kidney"
        try {
            QuartzCrypto.wordsToEntropy(bad)
            throw AssertionError("expected IllegalArgumentException")
        } catch (e: IllegalArgumentException) {
            // checksum or wordlist failure — expected
        }
    }

    @Test
    fun `unknown word is rejected`() {
        val bad = testWords.toMutableList()
        bad[0] = "notaword"
        try {
            QuartzCrypto.wordsToEntropy(bad)
            throw AssertionError("expected IllegalArgumentException")
        } catch (e: IllegalArgumentException) {
            // expected
        }
    }

    @Test
    fun `privkey derivation matches node derive_quartz_keypair`() {
        assertEquals(hex(testPriv).toList(), QuartzCrypto.privkeyFromMnemonic(testWords).toList())
    }

    @Test
    fun `ed25519 pubkey matches node`() {
        assertEquals(hex(testPub).toList(), QuartzCrypto.publicKeyFromPrivate(hex(testPriv)).toList())
    }

    @Test
    fun `address matches node`() {
        assertEquals(testAddr, QuartzCrypto.publicKeyToAddress(hex(testPub)))
    }

    @Test
    fun `address validation`() {
        assertTrue(QuartzCrypto.isValidAddress(testAddr))
        assertFalse(QuartzCrypto.isValidAddress(testAddr.dropLast(1) + "x"))
        assertFalse(QuartzCrypto.isValidAddress("1BitcoinEaterAddressDontSend"))
    }

    @Test
    fun `base58 round trip`() {
        val addr = QuartzCrypto.publicKeyToAddress(hex(testPub))
        assertEquals(addr, QuartzCrypto.base58Encode(QuartzCrypto.base58Decode(addr)))
        assertEquals(25, QuartzCrypto.base58Decode(addr).size)
    }

    @Test
    fun `sign and verify`() {
        val priv = hex(testPriv)
        val pub = QuartzCrypto.publicKeyFromPrivate(priv)
        // Exact message format the node reconstructs in /api/v1/send
        val msg = "${testAddr}${testAddr}150000000".toByteArray(Charsets.US_ASCII)
        val sig = QuartzCrypto.sign(priv, msg)
        assertEquals(64, sig.size)
        assertTrue(QuartzCrypto.verify(pub, msg, sig))
        assertFalse(QuartzCrypto.verify(pub, msg + 1, sig))
    }
}
