package com.quartz.wallet.crypto

import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Cross-implementation vectors — generated by the reference node
 * (reference-node/quartz/wallet.py + quantum_crypto.py; see
 * wallet/streams-vectors.json in the repo). If these fail, the app's
 * streams and the chain have diverged.
 */
class QuartzStreamsTest {

    private fun hex(s: String): ByteArray = s.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
    private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }

    private val seed = hex("1111111111111111111111111111111111111111111111111111111111111111")

    @Test
    fun `account seed matches reference`() {
        assertEquals(
            "9d58abd7395900bce925eafc28c8912c3a819895ca89d7c631ec8b7d24454432",
            QuartzStreams.streamAccountSeed(seed, 0).toHex()
        )
    }

    @Test
    fun `merkle root matches reference`() {
        assertEquals(
            "5c9c60fdb844353ad4758f531a8b8e4ae0d3cdba24028cb27f786eaed3b604e2",
            QuartzStreams.generateQuantumAddressRoot(
                QuartzStreams.streamAccountSeed(seed, 0)).toHex()
        )
    }

    @Test
    fun `stream addresses match reference`() {
        val expected = listOf(
            "Qr3CyjrBcJrSfQ8hMYpnjLHqk5CVP9mJFV",
            "R7frDxt3yUkMow75Y838Jm1q1KUxrzKg5i",
            "Qo8HX1Y14rWvmR36Eqdqphy62TG96AwcMi"
        )
        expected.forEachIndexed { i, addr ->
            assertEquals("stream address #$i", addr, QuartzStreams.streamAddressAt(seed, i))
        }
    }

    @Test
    fun `channel seed and addresses match reference`() {
        val chSeed = QuartzStreams.channelSeedFromWallet(seed, 41)
        assertEquals(
            "5b636180b65492d4a66071177b20bc802c1934a89adf519dd72082ec8eaf7571",
            QuartzStreams.channelStreamSeed(chSeed, 0).toHex()
        )
        val expected = listOf(
            "Qk5pfar2asP2MNSoHrJTQLz28cE3rb3QQm",
            "QmngtZNSxpnmeU6FrZvSeg5L6Mnu1FcB6Z",
            "QpVXqqGs1AEDmw2da7cts9HcWAadsNhPn1"
        )
        expected.forEachIndexed { i, addr ->
            assertEquals("channel address #$i", addr, QuartzStreams.channelAddressAt(chSeed, i))
        }
    }

    @Test
    fun `shared-secret addresses match reference`() {
        val shSeed = QuartzStreams.sharedSecretChannelSeed("s3cret".toByteArray())
        assertEquals("R7eU74UPVtKQt15oyg9Hc2ajcMa67jhtZk", QuartzStreams.channelAddressAt(shSeed, 0))
        assertEquals("R2cixoy9ssU8eQb5zrdPhXhcUeBUicYpck", QuartzStreams.channelAddressAt(shSeed, 1))
    }

    @Test
    fun `bundle json carries addresses only`() {
        val chSeed = QuartzStreams.channelSeedFromWallet(seed, 41)
        val json = QuartzStreams.bundleJson(chSeed, 41, 3)
        assert(json.contains("\"type\":\"quartz/payment-bundle\""))
        assert(json.contains("Qk5pfar2asP2MNSoHrJTQLz28cE3rb3QQm"))
        // No key material may ever appear in a bundle
        assert(!json.contains(seed.toHex()))
        assert(!json.contains(chSeed.toHex()))
    }
}
